package nihvostain.managers.gui.local;

import java.util.ListResourceBundle;

public class GuiLabels_ru extends ListResourceBundle {
    @Override
    protected Object[][] getContents() {
        return new Object[][]{
                {"button.auth", "Авторизация"},
                {"button.reg", "Регистрация"},
                {"label.login", "Логин"},
                {"label.password", "Пароль"},
                {"server.timeOut", "сервер временно не доступен"},
                {"wrong.login", "не верный логин"},
                {"wrong.password", "не верный пароль"},
                {"data.error", "ошибка передачи данных, попробуйте снова"},
                {"help", "помощь"},
                {"exit", "выход"},
                {"show", "показать"},
                {"info", "информация"},
                {"insert", "ввод"},
                {"update", "обновить"},
                {"remove_key", "удалить_по_ключу"},
                {"clear", "очистить"},
                {"execute_script", "выполнить_скрипт"},
                {"remove_lower", "удалить_меньшее"},
                {"replace_if_greater", "заменить_есл_больше"},
                {"remove_greater_key", "удалить_большие_ключи"},
                {"group_counting_by_semester_enum", "сгруппировать_по_учебной_группе"},
                {"filter_contains_name", "фильтр_содержание_имя"},
                {"filter_greater_than_group_admin", "фильтр_больший_чем_староста"},
                {"edit", "редактировать"},
                {"delete", "удалить"},
                {"visualize", "визуализация"},
                {"OK", "ок"},
                {"key", "ключ"},
                {"id", "ид"},
                {"name", "имя"},
                {"x", "x"},
                {"y", "y"},
                {"studentsCount", "количество студентов"},
                {"creationDate", "дата создания"},
                {"formOfEducation", "форма обучения"},
                {"semesterEnum", "семестр"},
                {"nameP", "имя старосты"},
                {"birthday", "день рождения"},
                {"passportID", "паспорт"},
                {"eyeColor", "цвет глаз"},
                {"hairColor", "цвет волос"},
                {"scriptName", "имя скрипта"},
                {"nameSubstring", "подстрока имени"},
                {"",""},
                {"recursion", "превышен лимит глубины рекурсии, проверь скрипт"},
                {"alien", "элемент другого пользователя"},
                {"wrong_name", "имя не может быть пустым"},
                {"wrong_X", "X должен быть типа Integer"},
                {"wrong_Y", "Y должен быть типа Double"},
                {"wrong_student_count", "кол-во студентов должно быть типа Long и больше нуля"},
                {"wrong_form_of_edu", "Такой формы обучения нет в списке"},
                {"wrong_semester_enum", "Такого семестра нет в списке"},
                {"wrong_name_P", "имя не может быть пустым"},
                {"wrong_birthday", "день рождения должен быть в формате 'dd-MM-yyyy'T'HH:mm:ssXXX'\\n\" +\n" +
                        "                        \"Пример: 25-07-2006T14:30:00+03:00"},
                {"wrong_passport_id", "Такого паспорта не существует или он не ваш"},
                {"wrong_eye", "Такого цвета в списке нет"},
                {"wrong_hair", "Такого цвета в списке нет"},
                {"goodParam", "все гуд"},
                {"existingKey", "такой ключ уже есть"},
                {"noKey", "нет такого ключа"},
                {"noID", "нет такого id"},
                {"notLongID", "id должен быть Long"},
                {"false", "все очень плохо"},
                {"fileNotFound", "нет файла с таким именем"},
                {"wrongParamInScript", "Неверные параметры для вызванной команды в скрипте"},
                {"wrongParam", "Неверные параметры для вызванной команды"},
                {"wrongCommand", "Неопознанная команда в скрипте"}
        };

    }
}
