package nihvostain.managers.gui.local;

import java.util.ListResourceBundle;

public class GuiLabels_sl extends ListResourceBundle {
    @Override
    protected Object[][] getContents() {
        return new Object[][]{
                {"button.auth", "Prijava"},
                {"button.reg", "Registracija"},
                {"label.login", "Uporabniško ime"},
                {"label.password", "Geslo"},
                {"server.timeOut", "Strežnik trenutno ni na voljo"},
                {"wrong.login", "Napačno uporabniško ime"},
                {"wrong.password", "Napačno geslo"},
                {"data.error", "Napaka pri prenosu podatkov, poskusite znova"},
                {"help", "Pomoč"},
                {"exit", "Izhod"},
                {"show", "Pokaži"},
                {"info", "Informacije"},
                {"insert", "Vnos"},
                {"update", "Posodobi"},
                {"remove_key", "Odstrani_po_ključi"},
                {"clear", "Počisti"},
                {"execute_script", "Zaženi_skript"},
                {"remove_lower", "Odstrani_nižjega"},
                {"replace_if_greater", "Zamenjaj_če_večje"},
                {"remove_greater_key", "Odstrani_večje_ključe"},
                {"group_counting_by_semester_enum", "Združi_po_semestru"},
                {"filter_contains_name", "Filter_vsebuje_ime"},
                {"filter_greater_than_group_admin", "Filter_več_kot_skupinski_admin"},
                {"edit", "Uredi"},
                {"delete", "Izbriši"},
                {"visualize", "Vizualiziraj"},
                {"OK", "V redu"},
                {"key", "Ključ"},
                {"id", "ID"},
                {"name", "Ime"},
                {"x", "x"},
                {"y", "y"},
                {"studentsCount", "Število študentov"},
                {"creationDate", "Datum ustvarjanja"},
                {"formOfEducation", "Oblika izobraževanja"},
                {"semesterEnum", "Semester"},
                {"nameP", "Ime starešine"},
                {"birthday", "Rojstni dan"},
                {"passportID", "Potni list"},
                {"eyeColor", "Barva oči"},
                {"hairColor", "Barva las"},
                {"scriptName", "Ime skripte"},
                {"nameSubstring", "Podniz imena"},
                {"", ""},
                {"recursion", "Presežena globina rekurzije, preverite skripto"},
                {"alien", "Element drugega uporabnika"},
                {"wrong_name", "Ime ne sme biti prazno"},
                {"wrong_X", "X mora biti tipa Integer"},
                {"wrong_Y", "Y mora biti tipa Double"},
                {"wrong_student_count", "Število študentov mora biti tipa Long in večje od nič"},
                {"wrong_form_of_edu", "Taka oblika izobraževanja ne obstaja"},
                {"wrong_semester_enum", "Tega semestra ni na seznamu"},
                {"wrong_name_P", "Ime ne sme biti prazno"},
                {"wrong_birthday", "Rojstni dan mora biti v formatu 'dd-MM-yyyy'T'HH:mm:ssXXX'\nPrimer: 25-07-2006T14:30:00+03:00"},
                {"wrong_passport_id", "Takšen potni list ne obstaja ali ni vaš"},
                {"wrong_eye", "Taka barva oči ni na seznamu"},
                {"wrong_hair", "Taka barva las ni na seznamu"},
                {"goodParam", "vse v redu"},
                {"existingKey", "tak ključ že obstaja"},
                {"noKey", "takšnega ključa ni"},
                {"noID", "takšnega ID-ja ni"},
                {"notLongID", "ID mora biti tipa Long"},
                {"false", "vse je zelo slabo"},
                {"fileNotFound", "Datoteke s takim imenom ni"},
                {"wrongParamInScript", "Napačni parametri za ukaz v skriptu"},
                {"wrongParam", "Napačni parametri za ukaz"},
                {"wrongCommand", "Neznan ukaz v skriptu"}
        };
    }
}
