package nihvostain.managers.gui.local;

import java.util.ListResourceBundle;

public class GuiLabels_el extends ListResourceBundle {
    @Override
    protected Object[][] getContents() {
        return new Object[][]{
                {"button.auth", "Σύνδεση"},
                {"button.reg", "Εγγραφή"},
                {"label.login", "Όνομα χρήστη"},
                {"label.password", "Κωδικός"},
                {"server.timeOut", "ο διακομιστής δεν είναι προσωρινά διαθέσιμος"},
                {"wrong.login", "λάθος όνομα χρήστη"},
                {"wrong.password", "λάθος κωδικός"},
                {"data.error", "σφάλμα μεταφοράς δεδομένων, δοκιμάστε ξανά"},
                {"help", "βοήθεια"},
                {"exit", "έξοδος"},
                {"show", "εμφάνιση"},
                {"info", "πληροφορίες"},
                {"insert", "εισαγωγή"},
                {"update", "ενημέρωση"},
                {"remove_key", "διαγραφή_με_κλειδί"},
                {"clear", "εκκαθάριση"},
                {"execute_script", "εκτέλεση_σεναρίου"},
                {"remove_lower", "διαγραφή_χαμηλότερων"},
                {"replace_if_greater", "αντικατάσταση_αν_μεγαλύτερο"},
                {"remove_greater_key", "διαγραφή_μεγαλύτερων_κλειδιών"},
                {"group_counting_by_semester_enum", "ομαδοποίηση_κατά_εξάμηνο"},
                {"filter_contains_name", "φίλτρο_περιέχει_όνομα"},
                {"filter_greater_than_group_admin", "φίλτρο_μεγαλύτερο_από_τον_αρχηγό"},
                {"edit", "επεξεργασία"},
                {"delete", "διαγραφή"},
                {"visualize", "οπτικοποίηση"},
                {"OK", "OK"},
                {"key", "κλειδί"},
                {"id", "ταυτότητα"},
                {"name", "όνομα"},
                {"x", "x"},
                {"y", "y"},
                {"studentsCount", "αριθμός φοιτητών"},
                {"creationDate", "ημερομηνία δημιουργίας"},
                {"formOfEducation", "μορφή εκπαίδευσης"},
                {"semesterEnum", "εξάμηνο"},
                {"nameP", "όνομα αρχηγού"},
                {"birthday", "ημερομηνία γέννησης"},
                {"passportID", "διαβατήριο"},
                {"eyeColor", "χρώμα ματιών"},
                {"hairColor", "χρώμα μαλλιών"},
                {"scriptName", "όνομα σεναρίου"},
                {"nameSubstring", "υπο-αλφαριθμητικό ονόματος"},
                {"", ""},
                {"recursion", "υπέρβαση βάθους αναδρομής, ελέγξτε το σενάριο"},
                {"alien", "στοιχείο άλλου χρήστη"},
                {"wrong_name", "το όνομα δεν μπορεί να είναι κενό"},
                {"wrong_X", "το X πρέπει να είναι τύπου Integer"},
                {"wrong_Y", "το Y πρέπει να είναι τύπου Double"},
                {"wrong_student_count", "ο αριθμός φοιτητών πρέπει να είναι τύπου Long και > 0"},
                {"wrong_form_of_edu", "Αυτή η μορφή εκπαίδευσης δεν υπάρχει"},
                {"wrong_semester_enum", "Αυτό το εξάμηνο δεν υπάρχει"},
                {"wrong_name_P", "το όνομα δεν μπορεί να είναι κενό"},
                {"wrong_birthday", "ημερομηνία γέννησης σε μορφή 'dd-MM-yyyy'T'HH:mm:ssXXX'\nΠ.χ.: 25-07-2006T14:30:00+03:00"},
                {"wrong_passport_id", "Το διαβατήριο δεν υπάρχει ή δεν είναι δικό σας"},
                {"wrong_eye", "Το χρώμα ματιών δεν υπάρχει"},
                {"wrong_hair", "Το χρώμα μαλλιών δεν υπάρχει"},
                {"goodParam", "όλα καλά"},
                {"existingKey", "υπάρχει ήδη αυτό το κλειδί"},
                {"noKey", "δεν υπάρχει τέτοιο κλειδί"},
                {"noID", "δεν υπάρχει τέτοιο ID"},
                {"notLongID", "το ID πρέπει να είναι Long"},
                {"false", "κάτι πήγε πολύ στραβά"},
                {"fileNotFound", "δεν βρέθηκε αρχείο με αυτό το όνομα"},
                {"wrongParamInScript", "Λανθασμένες παράμετροι στο σενάριο"},
                {"wrongParam", "Λανθασμένες παράμετροι"},
                {"wrongCommand", "Μη αναγνωρισμένη εντολή στο σενάριο"}
        };
    }
}
