package nihvostain.managers.gui.local;

import java.util.ListResourceBundle;

public class GuiLabels_es_PA extends ListResourceBundle {
    @Override
    protected Object[][] getContents() {
        return new Object[][]{
                {"button.auth", "Autenticación"},
                {"button.reg", "Registro"},
                {"label.login", "Usuario"},
                {"label.password", "Contraseña"},
                {"server.timeOut", "el servidor no está disponible temporalmente"},
                {"wrong.login", "usuario incorrecto"},
                {"wrong.password", "contraseña incorrecta"},
                {"data.error", "error de transferencia de datos, intente de nuevo"},
                {"help", "ayuda"},
                {"exit", "salir"},
                {"show", "mostrar"},
                {"info", "información"},
                {"insert", "insertar"},
                {"update", "actualizar"},
                {"remove_key", "eliminar_por_clave"},
                {"clear", "limpiar"},
                {"execute_script", "ejecutar_script"},
                {"remove_lower", "eliminar_menores"},
                {"replace_if_greater", "reemplazar_si_es_mayor"},
                {"remove_greater_key", "eliminar_claves_mayores"},
                {"group_counting_by_semester_enum", "agrupar_por_semestre"},
                {"filter_contains_name", "filtrar_contiene_nombre"},
                {"filter_greater_than_group_admin", "filtrar_mayor_que_admin"},
                {"edit", "editar"},
                {"delete", "eliminar"},
                {"visualize", "visualizar"},
                {"OK", "OK"},
                {"key", "clave"},
                {"id", "id"},
                {"name", "nombre"},
                {"x", "x"},
                {"y", "y"},
                {"studentsCount", "número de estudiantes"},
                {"creationDate", "fecha de creación"},
                {"formOfEducation", "forma de educación"},
                {"semesterEnum", "semestre"},
                {"nameP", "nombre del líder"},
                {"birthday", "cumpleaños"},
                {"passportID", "pasaporte"},
                {"eyeColor", "color de ojos"},
                {"hairColor", "color de cabello"},
                {"scriptName", "nombre del script"},
                {"nameSubstring", "subcadena de nombre"},
                {"", ""},
                {"recursion", "límite de profundidad de recursión superado, revise el script"},
                {"alien", "elemento de otro usuario"},
                {"wrong_name", "el nombre no puede estar vacío"},
                {"wrong_X", "X debe ser tipo Integer"},
                {"wrong_Y", "Y debe ser tipo Double"},
                {"wrong_student_count", "el número debe ser tipo Long y mayor que cero"},
                {"wrong_form_of_edu", "Esa forma de educación no está en la lista"},
                {"wrong_semester_enum", "Ese semestre no está en la lista"},
                {"wrong_name_P", "el nombre no puede estar vacío"},
                {"wrong_birthday", "la fecha debe tener el formato 'dd-MM-yyyy'T'HH:mm:ssXXX'\nEjemplo: 25-07-2006T14:30:00+03:00"},
                {"wrong_passport_id", "Ese pasaporte no existe o no es suyo"},
                {"wrong_eye", "Ese color de ojos no está en la lista"},
                {"wrong_hair", "Ese color de cabello no está en la lista"},
                {"goodParam", "todo bien"},
                {"existingKey", "ya existe esa clave"},
                {"noKey", "no existe esa clave"},
                {"noID", "no existe ese id"},
                {"notLongID", "el id debe ser tipo Long"},
                {"false", "todo salió muy mal"},
                {"fileNotFound", "no se encontró archivo con ese nombre"},
                {"wrongParamInScript", "Parámetros incorrectos en el script"},
                {"wrongParam", "Parámetros incorrectos"},
                {"wrongCommand", "Comando no reconocido en el script"}
        };
    }
}
